apiVersion: v1
kind: ConfigMap
metadata:
  name: novacrm-config
  namespace: novacrm-prod
data:
  NODE_ENV: "production"
  PORT: "4000"
  FRONTEND_PORT: "3000"
  REDIS_HOST: "novacrm-redis-service"
  REDIS_PORT: "6379"
  DATABASE_HOST: "novacrm-postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "novacrm_db"
  NEXT_PUBLIC_API_URL: "https://api.novacrm.com/api/v1"
---
apiVersion: v1
kind: Secret
metadata:
  name: novacrm-secrets
  namespace: novacrm-prod
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "NovaCrmProductionPostgresPassword2026!"
  DATABASE_URL: "postgresql://postgres:NovaCrmProductionPostgresPassword2026!@novacrm-postgres-service:5432/novacrm_db?schema=public&sslmode=prefer"
  JWT_SECRET: "nova_crm_production_high_security_jwt_secret_key_2026"
  REDIS_PASSWORD: ""
